### ISSUE TITLE
"LocationID" or "location_id"?

### ISSUE THREAD

**Issue by MuhammedZakir** [ajanian/KarabinerBluetoothKeyboardLocationUpdater#4]
`locationID` is used to match prop here -- https://github.com/ajanian/KarabinerBluetoothKeyboardLocationUpdater/blob/3d8a3607a95973dbb04d23b140e55bd54b6f7926/src/index.ts#L61
But KE uses `location_id`. To my understanding, this should not work, but you are already using this. So I presume it does. But I am honestly confused about how this actually works. An explanation would be helpful! Thanks and sorry for the trouble! :-)

**Comment by ajanian** [comment]
Great catch @MuhammedZakir.  I have some more changes in my local checkout that included the bug fix you noted.  When I originally pushed I must have pushed the wrong thing.  I picked up this change.

**Comment by MuhammedZakir** [comment]
That explains! 😅
